function [Timems, y_refm, y_currm, theta_ref_rawr, theta_ref_satr, theta_currr, Trial, V_motorV, tbl] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIMEMS, Y_REFM, Y_CURRM, THETA_REF_RAWR, THETA_REF_SATR,
%  THETA_CURRR, TRIAL, V_MOTORV] = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as
%  column vectors.
%
%  [TIMEMS, Y_REFM, Y_CURRM, THETA_REF_RAWR, THETA_REF_SATR,
%  THETA_CURRR, TRIAL, V_MOTORV] = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Timems, y_refm, y_currm, theta_ref_rawr, theta_ref_satr, theta_currr, Trial, V_motorV] = importfile("C:\Users\catie\Documents\Courses\mte 484\mte484\lab3\Experimental Logging\FirstTrial_360ms.txt", [6, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Nov-2025 13:58:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timems", "y_refm", "y_currm", "theta_ref_rawr", "theta_ref_satr", "theta_currr", "Trial", "V_motorV"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Timems = tbl.Timems;
y_refm = tbl.y_refm;
y_currm = tbl.y_currm;
theta_ref_rawr = tbl.theta_ref_rawr;
theta_ref_satr = tbl.theta_ref_satr;
theta_currr = tbl.theta_currr;
Trial = tbl.Trial;
V_motorV = tbl.V_motorV;
end