function [Timems, OriginalRefrad, FinalRefrad, Anglerad, TrialNum, TrialValue, U_ActualV, Ball] = importsinefile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIMEMS, ORIGINALREFRAD, FINALREFRAD, ANGLERAD, TRIALNUM, TRIALVALUE,
%  U_ACTUALV, BALL] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [TIMEMS, ORIGINALREFRAD, FINALREFRAD, ANGLERAD, TRIALNUM, TRIALVALUE,
%  U_ACTUALV, BALL] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [Timems, OriginalRefrad, FinalRefrad, Anglerad, TrialNum, TrialValue, U_ActualV, Ball] = importfile("C:\Users\catie\Documents\Courses\mte 484\mte484\lab2\logging\S12_BallSineTest.txt", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Nov-2025 18:39:35

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timems", "OriginalRefrad", "FinalRefrad", "Anglerad", "TrialNum", "TrialValue", "U_ActualV", "Ball"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";


% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Timems = tbl.Timems;
OriginalRefrad = tbl.OriginalRefrad;
FinalRefrad = tbl.FinalRefrad;
Anglerad = tbl.Anglerad;
TrialNum = tbl.TrialNum;
TrialValue = tbl.TrialValue;
U_ActualV = tbl.U_ActualV;
Ball = tbl.Ball;
end