%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Lucas\OneDrive - University of Waterloo\University\4A\MTE 484\Labs\Repo\lab2\logging\S12_LongBallSineTest.txt
%
% Auto-generated by MATLAB on 08-Nov-2025 17:36:41

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [5, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timems", "OriginalRefrad", "FinalRefrad", "Anglerad", "TrialNum", "TrialValue", "U_ActualV", "Ball"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable("C:\Users\Lucas\OneDrive - University of Waterloo\University\4A\MTE 484\Labs\Repo\lab2\logging\S12_LongBallSineTest.txt", opts);


%% Clear temporary variables
clear opts